### ISSUE TITLE
Add install_requires to handle dependencies

### ISSUE THREAD

**Issue by caseysoftware** [Clarify/clarify_python#1]
We should add a requirements.txt file to have the dependencies installed in a single step. The ideal would be to have this as part of the library install process itself.

Ref: https://pip.pypa.io/en/latest/user_guide.html#requirements-files

**Comment by grahamc** [comment]
Requirements files are more for pinning dependencies than listing them. You might compare it to a `composer.lock` file. An application depending on our tool has a requirements.txt, but a library should not.

The more correct route is to use the `install_requires` field of [setup.py](https://github.com/Clarify/clarify_python/blob/69ac0648de43e531c49aadfa106bdd6e50a30c69/setup.py#L34): https://packaging.python.org/en/latest/distributing.html#install-requires

##

**Comment by caseysoftware** [comment]
Ah thanks. Just found this which lays it out well:

https://packaging.python.org/en/latest/requirements.html

**Comment by irothschild** [comment]
Yes, adding deps to the setup is on P's TODO list for this module.

**Comment by murphy** [comment]
Fixed. Will be checking in 1.1.1 soon. Then on to 2.0.
